// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxazqtgnqtsbmfknltmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YXpxdGducXRzYm1ma25sdG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTk3NDcsImV4cCI6MjA3NDM5NTc0N30.veW7wLsLOiyKmVhiAcCSu6Gnd0GhPrYZsyNs4Yi_Rjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});